config/routes.rb
Rails.application.routes.draw do
  resources :signins

  resources :logins
 root  'user#login'
  get 'user/login' => 'user#login'
  get 'user/signup', to: 'user#signup'
  get 'user/json', to: 'user#json'
  get 'user/home'
  get  ':controller(/:action(/:id))'

 resources :article
  get 'welcome/nav', to: 'welcome#nav'

  get 'welcome/contact'
      get 'welcome/about'
  get 'user/data'

  get 'welcome/about'

  get 'welcome/home', to: 'welcome#home'

end

app/models/login.rb
class Login < ActiveRecord::Base
  has_secure_password
end

app/models/signin.rb
class Signin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def new

  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to logins_url, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to logins_url, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/signins_controller.rb
class SigninsController < ApplicationController
  before_action :set_signin, only: [:show, :edit, :update, :destroy]

  # GET /signins
  # GET /signins.json
  def index
    @signins = Signin.all
  end

  # GET /signins/1
  # GET /signins/1.json
  def show
  end

  # GET /signins/new
  def new
    @signin = Signin.new
  end

  # GET /signins/1/edit
  def edit
  end

  # POST /signins
  # POST /signins.json
  def create
    @signin = Signin.new(signin_params)

    respond_to do |format|
      if @signin.save
        format.html { redirect_to @signin, notice: 'Signin was successfully created.' }
        format.json { render :show, status: :created, location: @signin }
      else
        format.html { render :new }
        format.json { render json: @signin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signins/1
  # PATCH/PUT /signins/1.json
  def update
    respond_to do |format|
      if @signin.update(signin_params)
        format.html { redirect_to @signin, notice: 'Signin was successfully updated.' }
        format.json { render :show, status: :ok, location: @signin }
      else
        format.html { render :edit }
        format.json { render json: @signin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signins/1
  # DELETE /signins/1.json
  def destroy
    @signin.destroy
    respond_to do |format|
      format.html { redirect_to signins_url, notice: 'Signin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signin
      @signin = Signin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signin_params
      params.require(:signin).permit(:email, :password)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def home

  end
  def login

  end
  def signup

  end
  def data

  end
  def json


  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
  def contact
  end
  def about
  end
  def nav

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
  def form_with
  end


end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/signins_helper.rb
module SigninsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article/new.html.erb
<%= form_for(@article) do |f| %>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width ,initial-scale=1.0">
  <%= stylesheet_link_tag 'home.css' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>


</head>
<body>



<div class="container ">

  <div style="background-color: #DADADA" class="jumbotron text-warning bg-warning ">
    <ul>
      <li><%= link_to "log in" , user_login_path %></li>
      <li><%= link_to "sign up" , user_signup_path %></li>
    </ul>
  </div>
  <div class="row">




  </div>






<%= yield %>


  <div  style="background-color: #DADADA" class="jumbotron text-warning bg-dark ">
   <center>copy right</center>
  </div>
  <div class="row">




  </div>

</div>

</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.email %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @login.email %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/signins/_form.html.erb
<%= form_for(@signin) do |f| %>
  <% if @signin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signin.errors.count, "error") %> prohibited this signin from being saved:</h2>

      <ul>
      <% @signin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signins/edit.html.erb
<h1>Editing signin</h1>

<%= render 'form' %>

<%= link_to 'Show', @signin %> |
<%= link_to 'Back', signins_path %>

app/views/signins/index.html.erb
<h1>Listing signins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signins.each do |signin| %>
      <tr>
        <td><%= signin.email %></td>
        <td><%= signin.password %></td>
        <td><%= link_to 'Show', signin %></td>
        <td><%= link_to 'Edit', edit_signin_path(signin) %></td>
        <td><%= link_to 'Destroy', signin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signin', new_signin_path %>

app/views/signins/new.html.erb
<h1>New signin</h1>

<%= render 'form' %>

<%= link_to 'Back', signins_path %>

app/views/signins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @signin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @signin.password %>
</p>

<%= link_to 'Edit', edit_signin_path(@signin) %> |
<%= link_to 'Back', signins_path %>

app/views/user/data.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=divice-width , initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

</head>
<body>







<style>
  p{
    font-family: Algerian;
  }
</style>
<div align="center" class="jumbotron text-center">
  <div style="font-family: 'Cooper Black'; font-size: 3em;">User's Detail</div>
  <p>First Name is: <span id="fn"></span> </p>
  <p>Last Name is: <span id="ln"></span> </p>
  <p>Email is: <span id="ema"></span> </p>
  <p>Password is: <span id="pas"></span> </p>

  <p id="demo"></p>

</div>









<script>










    var str1= window.location.search;
    var str =str1.replace("%40",'@');
    var res = str.split("=");
    var fn=  res['1'];
    var fname=fn.split("&");
    document.getElementById("fn").innerHTML =fname['0'];


    var ln=  res['2'];
    var l_name=ln.split("&");
    document.getElementById("ln").innerHTML =l_name['0'];

    var e=  res['3'];
    var email=e.split("&");
    document.getElementById("ema").innerHTML =email['0'];

    var p=  res['4'];
    var pass=p.split("&");
    document.getElementById("pas").innerHTML =pass['0'];
 var d={
     "firstname":fname['0'],
     "lastname":l_name['0'],
     "email":email['0'],
     "password":pass['0']
 }
var st=JSON.stringify(d);



 var ob=JSON.parse(st);
 for( x in ob){
     document.getElementById('demo').innerHTML=st;
 }





</script>

</body>
</html>

app/views/user/home.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width ,initial-scale=1.0">
  <%= stylesheet_link_tag 'home.css' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

</head>
<body  >
<div class="container ">

<div class="jumbotron text-warning ">
  <ul>
    <li><%= link_to "Log In" , user_login_path%></li>
    <li><%= link_to "Sign Up" , user_signup_path%></li>
  </ul>
</div>
<div class="row">




</div>

</div>

</body>

</html>
<html>

app/views/user/login.html.erb
<!doctype html>
<html>
<head>

  <%= stylesheet_link_tag "style1.css" %>
  <%= javascript_include_tag "script1.js" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>
<script>

    function loadDoc5() {

        var email=document.getElementById('le').value;
        var pass=document.getElementById("lp").value;
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var d = this.responseText;
                var ob = JSON.parse(d);
                var em = ob.email;
                var pas = ob.pass;
               if(em==email && pas==pass){
                   alert("you are loged in");
               }
               else{
                   alert("wrong username or password");
                   return false;
               }
            }
        };
        xhttp.open("GET", "data.json", true);
        xhttp.send();
    }

</script>

<div  style="margin: 50px" align="center" class="jumbotron">
  <table rows="9" cols="2 " cellspacing="10" >
    <form onsubmit="return loadDoc5();">
      <tr><th style="font-family: cooper;font-size: 3em;"  class="text-center" colspan="2">Sign In</th></tr>
      <tr>
      <tr>

        <td colspan="2">
          <input type="text" id="le" placeholder="Email" class="in-field"/><br>
        </td>
      </tr>

      <tr>

        <td colspan="2">
          <input type="password"  id="lp" placeholder="Password" class="in-field"/><br>
        </td>
      </tr>

      <tr>

        <td colspan="2" style="text-align: center">
          <input type="submit" onclick="f1();" value="Log in"  class=""/><br>
        </td>
      </tr>
      <tr>
        <td colspan="2"><span>Register here</span><%= link_to "sign up" , user_signup_path %></td>
      </tr>

    </form>
  </table>
</div>
</body>
</html>

app/views/user/signup.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=divice-width , initial-scale=1.0">
  <%= stylesheet_link_tag "style1.css" %>
  <%= javascript_include_tag "script1.js" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

</head>
<body>

<div  style="margin: 50px" align="center" class=" jumbotron">
  <table rows="9" cols="2 " cellspacing="10" >
    <form method="get" action="data" onsubmit="return f();">
    <tr><th style="font-family: cooper;font-size: 3em;" class="text-center" colspan="2">Sign UP</th></tr>
    <tr>

      <td colspan="2">
        <input type="text"  id="fn" placeholder="First Name" name="fn" class="in-field"/><br>
      </td>
    </tr>


      <tr>

        <td colspan="2">
          <input type="text"  id="ln" placeholder="Last Name" name="ln" class="in-field"/><br>
        </td>
      </tr>


      <tr>

        <td colspan="2">
          <input type="text"  id="email" placeholder="Email" name="email" class="in-field"/><br>
        </td>
      </tr>

      <tr>

        <td colspan="2">
          <input type="password"  id="pass" placeholder="Password"  name="pass" class="in-field"/><br>
        </td>
      </tr>


      <tr>

        <td colspan="2">
          <input type="password"  id="c_pass" placeholder="Confirm Password" class="in-field"/><br>
        </td>
      </tr>


      <tr>

        <td colspan="2" style="text-align: center">
          <input type="submit" value="Sign Up" onclick="f();" class=""/><br>
        </td>
      </tr>
<tr>
  <td colspan="2"><span>Already Register</span></td><td><%= link_to "log in" , user_login_path %></td>
</tr>
    </form>
  </table>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>this is about page</h1>

app/views/welcome/contact.html.erb


<h1>this is contact us page</h1>

app/views/welcome/home.html.erb
<h1>this is home page</h1>

<% File.open('login.rb', 'r') do |f1| %>
    <% while line = f1.gets %>
        <%=puts line %>
    <%  end %>
<%  end %>

app/views/welcome/nav.html.erb
<!DOCTYPE html>
<html>
<body>

<button type="button" onclick="loadDoc()">home</button>
<button type="button" onclick="loadDoc2()">contact</button>
<button type="button" onclick="loadDoc1()">about</button>


<div id="demo">
 <h1>welcome</h1>

</div>

<script>
    function loadDoc() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("demo").innerHTML =
                    this.responseText;
            }
        };
        xhttp.open("GET", "home", true);
        xhttp.send();
    }
    function loadDoc1() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("demo").innerHTML =
                    this.responseText;
            }
        };
        xhttp.open("GET", "about", true);
        xhttp.send();
    }
    function loadDoc2() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("demo").innerHTML =
                    this.responseText;
            }
        };
        xhttp.open("GET", "contact", true);
        xhttp.send();
    }
</script>

</body>
</html>